// ============================================================
//  作品資料（首頁和第二頁共用這一份，只要改這裡）
//  ★ 如果你之前在 App.vue 裡改過自己的作品 / 圖片，
//    把那份 works 陣列的內容複製貼到這裡的 [ ... ] 中間。
// ============================================================
export const works = [
  {
    id: 1,
    type: 'image',
    title: '晨間習作',
    subtitle: '攝影 · 2024',
    year: '2024',
    image: '/works/01.jpg',
    description: '在這裡寫下這件作品的故事、媒材、想法……',
  },
  {
    id: 2,
    type: 'image',
    title: '城市切片',
    subtitle: '平面設計 · 2024',
    year: '2024',
    image: '/works/02.jpg',
    description: '這是第二件作品的介紹文字。',
  },
  {
    id: 3,
    type: 'image',
    title: '無聲對話',
    subtitle: '插畫 · 2025',
    year: '2025',
    image: '/works/03.jpg',
    description: '這是第三件作品的介紹文字。',
  },
  {
    id: 4,
    type: 'image',
    title: '光的容器',
    subtitle: '裝置 · 2025',
    year: '2025',
    image: '/works/04.jpg',
    description: '這是第四件作品的介紹文字。',
  },
  {
    id: 5,
    type: 'video',
    title: 'Liminal_Fade - au6xu 65 ru4',
    subtitle: '動態影像 · 2025',
    year: '2025',
    image: '/works/Liminal Fade.jpg',
    video: 'https://youtu.be/embed/68qgdzrjplc',
    description: '彌留之際= au6xu 65 ru4 《Liminal Fade》｜創作理念在《Liminal Fade》中，我以太空人穿越宇宙、雲層、海洋直至海底的視覺旅程，描繪一段模糊於夢境與現實之間的「臨界狀態」（liminal state）。苔蘚與花朵覆蓋的太空衣象徵自然對人造的回收，而從宇宙墜入深海的過程，則反映出自我意識的逐層剝離與沉潛。本作品結合AI生成影像與實拍素材，實驗性地將弗洛伊德的夢境理論與人工智慧的無意識演算機制並置，企圖在無序與秩序之間探索創作的本質。我試圖將夢境視為一種創作語言，將AI視為夢的延伸者，進一步思考：若AI與人類同樣生成夢境，我們是否仍能辨認什麼是真實？作品同時回應波德里亞的「超現實」理論與馬庫斯·杜·索托伊對AI創造力的探討，藉由視覺敘事與詩意象徵，質疑個體性、記憶、創造與存在的界線。《Liminal Fade》不僅是一段影像旅程，更是一場關於人機共創、意識轉換與存在意義的沈思。',
  },
  {
    id: 6,
    type: 'image',
    title: '紙上漫遊',
    subtitle: '手作書 · 2026',
    year: '2026',
    image: '/works/06.jpg',
    description: '這是第六件作品的介紹文字。',
  },
  {
    id: 7,
    type: 'image',
    title: '紙上漫遊',
    subtitle: '手作書 · 2026',
    year: '2026',
    image: '/works/07.jpg',
    description: '這是第七件作品的介紹文字。',
  },
  {
    id: 8,
    type: 'image',
    title: '紙上漫遊',
    subtitle: '手作書 · 2026',
    year: '2026',
    image: '/works/08.jpg',
    description: '這是第八件作品的介紹文字。',
  },
]
